[features]
seeds = false
[programs.localnet]
solana_mail_anchor = "DsKeiZjVAnaUY8uNcEeqh5jsz8tRXvU29uoMkiewF1Hg"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/muhammadtalhadar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
